version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    # --- Core correctness ---
    - govet # fast: compiler-backed static checks
    - errcheck # fast: unhandled errors
    - staticcheck # slow: deep SSA checks
    - exhaustive # slow: exhaustive switch/map
    - gosec # slow: security scanning
    - unused # fast: unused code detection
    - ineffassign # fast: ineffectual assignments

    # --- Style & idioms ---
    - revive # fast: modern golint replacement
    - misspell # fast: typos and spelling
    - modernize
    - exptostd # slow: experimental to stdlib
    - gocheckcompilerdirectives # fast: compiler directive checks
    - godox # fast: TODO/FIXME comments
    - godoclint # fast: godoc comments style
    - nakedret # fast: no naked returns
    - nilnesserr # fast: nilness checks
    - nilnil # fast: Checks that there is no simultaneous return of nil error and an invalid value.
    - nolintlint # fast: checks correctness of nolint directives
    - prealloc # fast: preallocate slices
    - predeclared # fast: avoid shadowing predeclared identifiers
    - protogetter # fast: avoid inefficient protobuf getters
    - unconvert # fast: unnecessary type conversions
    - usestdlibvars # fast: use stdlib vars
    - whitespace # fast: detect whitespace issues

    # --- Maintainability & performance ---
    - gocritic # fast: style and perf patterns
    - perfsprint # fast: avoid fmt.Sprintf misuse

    # --- Context & resource safety ---
    - bodyclose # fast: detect unclosed response bodies
    - copyloopvar # fast: closure capture safety
    - noctx # fast: context propagation checks

    # --- Testing correctness ---
    - testifylint # fast: misuse of testify/assert
    - thelper # fast: missing t.Helper()
    - paralleltest # fast: missing t.Parallel()
  settings:
    modernize:
      disable:
        # Avoid suggestions of changing interface{} to any.
        - any
    godoclint:
      # Default set of rules to enable.
      # Possible values are: `basic`, `all` or `none`.
      # Default: `basic` (enables `pkg-doc`, `single-pkg-doc`, `start-with-name`, and `deprecated`)
      default: none
      # List of rules to enable in addition to the default set.
      # Default: empty
      enable:
        # Check proper package-level godoc, if any.
        # https://github.com/godoc-lint/godoc-lint?tab=readme-ov-file#pkg-doc
        - pkg-doc
        # Assert at most one godoc per package.
        # https://github.com/godoc-lint/godoc-lint?tab=readme-ov-file#single-pkg-doc
        - single-pkg-doc
        # Assert symbol godocs start with the symbol name.
        # https://github.com/godoc-lint/godoc-lint?tab=readme-ov-file#start-with-name
        - start-with-name
        # Require godoc for all public symbols.
        # https://github.com/godoc-lint/godoc-lint?tab=readme-ov-file#require-doc
        - require-doc
        # Assert correct formatting of deprecation notes.
        # https://github.com/godoc-lint/godoc-lint?tab=readme-ov-file#deprecated
        - deprecated
    nakedret:
      # Make an issue if func has more lines of code than this setting, and it has naked returns.
      # Default: 30
      max-func-lines: 0
    govet:
      enable-all: true
      disable:
        - fieldalignment # too noisy for aligned structs
    gocritic:
      disabled-checks:
        - hugeParam
      enabled-tags:
        - performance
        - diagnostic
        - style
    exhaustive:
      check:
        - switch
        - map
      default-signifies-exhaustive: true
      default-case-required: false
    revive:
      confidence: 0.7
      severity: warning
      rules:
        - name: atomic
          severity: warning
          disabled: false
        - name: bare-return
          severity: warning
          disabled: false
        - name: blank-imports
          severity: warning
          disabled: false
        - name: bool-literal-in-expr
          severity: warning
          disabled: false
        - name: call-to-gc
          severity: warning
          disabled: false
        - name: constant-logical-expr
          severity: warning
          disabled: false
        - name: context-as-argument
          arguments:
            - allowTypesBefore: "*testing.T,*github.com/user/repo/testing.Harness"
          severity: warning
          disabled: false
        - name: context-keys-type
          severity: warning
          disabled: false
        - name: datarace
          severity: warning
          disabled: false
        - name: deep-exit
          severity: warning
          disabled: false
        - name: defer
          severity: warning
          disabled: false
        - name: dot-imports
          severity: warning
          disabled: false
        - name: duplicated-imports
          severity: warning
          disabled: false
        - name: early-return
          arguments:
            - preserveScope
          severity: warning
          disabled: false
        - name: empty-block
          severity: warning
          disabled: false
        - name: empty-lines
          severity: warning
          disabled: false
        - name: error-naming
          severity: warning
          disabled: false
        - name: error-return
          severity: warning
          disabled: false
        - name: error-strings
          severity: warning
          disabled: false
        - name: errorf
          severity: warning
          disabled: false
        - name: exported
          arguments:
            - checkPrivateReceivers
            - disableStutteringCheck
            - sayRepetitiveInsteadOfStutters
            - checkPublicInterface
            - disableChecksOnFunctions
          severity: warning
          disabled: false
        - name: flag-parameter
          severity: warning
          disabled: true
        - name: get-return
          severity: warning
          disabled: false
        - name: identical-branches
          severity: warning
          disabled: false
        - name: if-return
          severity: warning
          disabled: false
        - name: import-shadowing
          severity: warning
          disabled: false
        - name: increment-decrement
          severity: warning
          disabled: false
        - name: indent-error-flow
          arguments:
            - preserveScope
          severity: warning
          disabled: false
        - name: modifies-parameter
          severity: warning
          disabled: false
        - name: modifies-value-receiver
          severity: warning
          disabled: false
        - name: optimize-operands-order
          severity: warning
          disabled: false
        - name: range
          severity: warning
          disabled: false
        - name: range-val-in-closure
          severity: warning
          disabled: false
        - name: receiver-naming
          severity: warning
          disabled: false
        - name: redefines-builtin-id
          severity: warning
          disabled: false
        - name: redundant-import-alias
          severity: warning
          disabled: false
        - name: string-of-int
          severity: warning
          disabled: false
        - name: struct-tag
          severity: warning
          disabled: false
        - name: superfluous-else
          arguments:
            - preserveScope
          severity: warning
          disabled: false
        - name: time-equal
          severity: warning
          disabled: false
        - name: time-naming
          severity: warning
          disabled: false
        - name: unchecked-type-assertion
          arguments:
            - acceptIgnoredAssertionResult: true
          severity: warning
          disabled: false
        - name: unconditional-recursion
          severity: warning
          disabled: false
        - name: unexported-naming
          severity: warning
          disabled: false
        - name: unexported-return
          severity: warning
          disabled: false
        - name: unhandled-error
          arguments:
            - fmt.Printf
            - fmt.Print
            - fmt.Println
          severity: warning
          disabled: false
        - name: unnecessary-stmt
          severity: warning
          disabled: false
        - name: unreachable-code
          severity: warning
          disabled: false
        - name: unused-parameter
          arguments:
            - allowRegex: ^_
          severity: warning
          disabled: false
        - name: unused-receiver
          arguments:
            - allowRegex: ^_
          severity: warning
          disabled: false
        - name: useless-break
          severity: warning
          disabled: false
        - name: waitgroup-by-value
          severity: warning
          disabled: false
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: "ST1000:"
      - linters:
          - lll
        source: "^//go:generate "
      - path: _test\.go
        linters:
          - godoclint
          - gosec
