services:
  grafana:
    container_name: 'factry-historian-datasource'
    cap_add:
      - SYS_PTRACE
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.factry-historian-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: factry-historian-datasource
      GF_FEATURE_TOGGLES_ENABLE: 'sqlExpressions'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-oss}
        grafana_version: ${GRAFANA_VERSION:-latest}
        development: ${DEVELOPMENT:-true}
    ports:
      - 3001:3000/tcp
      - 2345:2345/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/factry-historian-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/factry-historian-datasource
      - grafana-data:/var/lib/grafana
      - go-mod:/root/go/pkg/mod
volumes:
  grafana-data:
    driver: local
  go-mod:
