version: '3.0'

services:
  grafana:
    platform: linux/amd64
    container_name: 'factry-historian-datasource'
    cap_add:
      - SYS_PTRACE
    environment:
      - DEBUG=$DEBUG
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-oss}
        grafana_version: ${GRAFANA_VERSION:-latest}
    ports:
      - 3001:3000/tcp
      - 2345:2345/tcp
      - 1234:1234/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/factry-historian-datasource
      - ./provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
volumes:
  grafana-data:
    driver: local
